name: 文件夹移动

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pyinstaller-build:
    runs-on: windows-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          # 由于tkinter是Python的标准库，不需要通过pip安装
          # 这里我们只安装shutil和os，因为它们在代码中被直接导入使用
          python -m pip install --upgrade pip
          pip install shutil
          pip install os

      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: '1.py'
          upload_exe_with_name: '文件夹移动.exe'
          options: --onefile

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: executable
          path: 文件移动.exe
