name: 文件夹移动

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pyinstaller-build:
    runs-on: windows-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install shutil
          python -m pip install os
          python -m pip install numpy

      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: '1.py'
          upload_exe_with_name: '文件移动'
          options: --onefile, --name "douban", --windowed
